version: '3'

services:
  db:
    image: mariadb:${MARIADB_IMAGE}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!5up3reXtr45trong5tring%
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  redis:
    image: redis:${REDIS_IMAGE}
    restart: always

  app:
    image: nextcloud:${NEXTCLOUD_IMAGE}
    container_name: overcloud_app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ${NEXTCLOUD_ROOT}/data/:${DATA_DIR}
      - ${CONFIG_DIR}/nextcloud/overcloud-recommended.ini:/usr/local/etc/php/conf.d/overcloud-recommended.ini
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_DATA_DIR=${DATA_DIR}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_FQDN}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    depends_on:
      - db
      - redis

  web:
    image: nginx:${NGINX_IMAGE}
    container_name: overcloud_web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - proxy-tier

  cron:
    image: nextcloud:${NEXTCLOUD_IMAGE}
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:

networks:
  proxy-tier:
    external:
      name: npm_proxy
